package Vistas;

import Modelos.Casa;
import Modelos.Departamento;
import Modelos.Inmobiliaria;
import Modelos.Propiedad;
import java.util.Objects;

public class VentanaInmobiliaria extends javax.swing.JFrame {

    Inmobiliaria inmobiliaria = new Inmobiliaria();
    Propiedad nuevaPropiedad = null;

    public VentanaInmobiliaria() {
        initComponents();
        cboxGarage.setVisible(false);
        txtPrecioExpensas.setVisible(false); //No se puede ver un campo al inicio del programa
        txtCantInquilinos.setText("0"); // Seteo un txt con 0 para que no de error el metodo constructor
        cboTipoPropiedad.setSelectedIndex(0); //ComboBox tiene seleccionado el primer item
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtCantHabitaciones = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cboxComercial = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCantInquilinos = new javax.swing.JTextField();
        btnCargar = new javax.swing.JButton();
        cboTipoPropiedad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboxGarage = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        txtPrecioExpensas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaInmobiliaria = new javax.swing.JList<>();
        btnCargarLista = new javax.swing.JButton();
        lblPrecioAlquiler = new javax.swing.JLabel();
        lblMontoPromedio2Inquilinos = new javax.swing.JLabel();
        lblCasas3HabitacionesGarage = new javax.swing.JLabel();
        btnMetodos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Propiedades");

        jLabel2.setText("Dirección");

        jLabel3.setText("Cantidad de habitaciones");

        jLabel4.setText("Precio base");

        cboxComercial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxComercialActionPerformed(evt);
            }
        });

        jLabel5.setText("Uso comercial");

        jLabel6.setText("Cantidad de inquilinos");

        btnCargar.setText("Cargar propiedad");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        cboTipoPropiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Departamento" }));
        cboTipoPropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoPropiedadActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de propiedad");

        jLabel8.setText("Garage");

        jLabel9.setText("Precio expensas");

        jScrollPane1.setViewportView(listaInmobiliaria);

        btnCargarLista.setText("Cargar lista");
        btnCargarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarListaActionPerformed(evt);
            }
        });

        lblPrecioAlquiler.setText("Precio alquiler:");

        lblMontoPromedio2Inquilinos.setText("Monto promedio de propiedades con 2 inquilinos:");

        lblCasas3HabitacionesGarage.setText("Casas con 3 habitaciones o mas y con garage:");

        btnMetodos.setText("Mostrar metodos");
        btnMetodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMetodos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCargarLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCargar)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPrecioExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxGarage)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboxComercial)
                                            .addComponent(txtCantInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cboTipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(163, 163, 163)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCasas3HabitacionesGarage)
                                            .addComponent(lblMontoPromedio2Inquilinos)
                                            .addComponent(lblPrecioAlquiler))))
                                .addContainerGap(73, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCantHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecioAlquiler))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(cboxComercial))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCantInquilinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblMontoPromedio2Inquilinos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cboTipoPropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblCasas3HabitacionesGarage)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cboxGarage, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecioExpensas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargar)
                    .addComponent(btnCargarLista)
                    .addComponent(btnMetodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        if (cboTipoPropiedad.getSelectedItem() == "Casa") {
            String direccion = txtDireccion.getText();
            int cantHabitaciones = Integer.parseInt(txtCantHabitaciones.getText());
            double precioBase = Double.parseDouble(txtPrecio.getText());
            boolean usoComercial = cboxComercial.isSelected();
            int cantInquilinos = Integer.parseInt(txtCantInquilinos.getText());
            boolean garage = cboxGarage.isSelected();

            nuevaPropiedad = new Casa(direccion, cantHabitaciones, precioBase, usoComercial, cantInquilinos, garage);

        } else {
            String direccion = txtDireccion.getText();
            int cantHabitaciones = Integer.parseInt(txtCantHabitaciones.getText());
            double precioBase = Double.parseDouble(txtPrecio.getText());
            boolean usoComercial = cboxComercial.isSelected();
            int cantInquilinos = Integer.parseInt(txtCantInquilinos.getText());
            double precioExpensas = Double.parseDouble(txtPrecioExpensas.getText());

            nuevaPropiedad = new Departamento(direccion, cantHabitaciones, precioBase, usoComercial, cantInquilinos, precioExpensas);
        }

        inmobiliaria.agregarPropiedad(nuevaPropiedad);

    }//GEN-LAST:event_btnCargarActionPerformed

    private void cboTipoPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoPropiedadActionPerformed
        if (cboTipoPropiedad.getSelectedItem() == "Casa") {
            cboxGarage.setVisible(true);
            txtPrecioExpensas.setVisible(false);
        } else {
            cboxGarage.setVisible(false);
            txtPrecioExpensas.setVisible(true);
        }
    }//GEN-LAST:event_cboTipoPropiedadActionPerformed

    private void btnCargarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarListaActionPerformed
        listaInmobiliaria.setListData(inmobiliaria.getListaPropiedad().toArray());
    }//GEN-LAST:event_btnCargarListaActionPerformed

    private void cboxComercialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxComercialActionPerformed
        if(cboxComercial.isSelected()){
            txtCantInquilinos.setVisible(false);
        }
        if(cboxComercial.isSelected() == false){
            txtCantInquilinos.setVisible(true);
        }
    }//GEN-LAST:event_cboxComercialActionPerformed

    private void btnMetodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodosActionPerformed
        lblPrecioAlquiler.setText("Precio alquiler: $" + inmobiliaria.precioAlquiler());
        lblMontoPromedio2Inquilinos.setText("Monto promedio de propiedades con 2 inquilinos: $" + inmobiliaria.promedio2Inquilinos());
        lblCasas3HabitacionesGarage.setText("Casas con 3 habitaciones o mas y con garage: " + inmobiliaria.cantCasasConHabitacion());
    }//GEN-LAST:event_btnMetodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInmobiliaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInmobiliaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnCargarLista;
    private javax.swing.JButton btnMetodos;
    private javax.swing.JComboBox<String> cboTipoPropiedad;
    private javax.swing.JCheckBox cboxComercial;
    private javax.swing.JCheckBox cboxGarage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCasas3HabitacionesGarage;
    private javax.swing.JLabel lblMontoPromedio2Inquilinos;
    private javax.swing.JLabel lblPrecioAlquiler;
    private javax.swing.JList<Object> listaInmobiliaria;
    private javax.swing.JTextField txtCantHabitaciones;
    private javax.swing.JTextField txtCantInquilinos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioExpensas;
    // End of variables declaration//GEN-END:variables
}
